### ISSUE TITLE
/routes fails to run on python3

### ISSUE THREAD

**Issue by MJRinne** [aalto-trafficsense/regular-routes-server#39]
Apparently something wrong gets compared for heap items in python3. This is the error I get:

````Traceback (most recent call last):
  File "/Users/Mikko/Dev/virtualenv/regular-routes-python3/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/Mikko/Dev/virtualenv/regular-routes-python3/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/Mikko/Dev/virtualenv/regular-routes-python3/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Mikko/Dev/virtualenv/regular-routes-python3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/Mikko/Dev/virtualenv/regular-routes-python3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Mikko/Dev/virtualenv/regular-routes-python3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Mikko/Dev/virtualenv/regular-routes-python3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Mikko/Dev/virtualenv/regular-routes-python3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/Mikko/Dev/virtualenv/regular-routes-python3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Mikko/Dev/virtualenv/regular-routes-python3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Mikko/Dev/Python/regular-routes-server/siteserver.py", line 397, in routes_json
    return common_routes_json(request, db, user_id)
  File "/Users/Mikko/Dev/Python/regular-routes-server/pyfiles/server_common.py", line 115, in common_routes_json
    clustered = list(get_routes(db, 1.0/3, user, date_start, date_end))
  File "/Users/Mikko/Dev/Python/regular-routes-server/pyfiles/routes.py", line 101, in get_routes
    clusters, route_merge, proto_distance, threshold)
  File "/Users/Mikko/Dev/Python/regular-routes-server/pyfiles/common_helpers.py", line 673, in do_cluster
    item[:] = heapitem(item[2], (x[2] for x in heap))
  File "/Users/Mikko/Dev/Python/regular-routes-server/pyfiles/common_helpers.py", line 664, in heapitem
    d1] for d1 in dests if d1 is not d0)
TypeError: '<' not supported between instances of 'dict' and 'dict'
````

The related code is in `heapitem` in [common_helpers.py](https://github.com/aalto-trafficsense/regular-routes-server/blob/master/pyfiles/common_helpers.py).

Not urgent, as `/routes` is currently not enabled for general users.

**Comment by ttolv** [comment]
```
def heapitem(d0, dests):
    return (min([distfun(d0, d1), d1] for d1 in dests if d1 is not d0) + [d0])

dests = [{1:2}, {1:4}, {1:6}, {1:8}]
distfun = lambda a, b: abs(a[1] - b[1])
heapitem(dests[0], dests)
[2, {1: 4}, {1: 2}]

dests = [{1:2}, {1:4}, {1:6}, {1:8}, {1:0}]
heapitem(dests[0], dests)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in heapitem
TypeError: '<' not supported between instances of 'dict' and 'dict'
```
Ah. In the case of two equally near neighbors, the comparison of lists will fall from the calculated distance element to the next element which is the neighbor destination structure — for the purposes of clustering it's safely arbitrary in py2, but py3 apparently does not like to < dicts

**Comment by MJRinne** [comment]
Looks as if the same thing happened this afternoon on the `regularroutes-api` on a request of destinations (no fix implemented there yet):

    [2018-11-05 15:27:29,302] ERROR in app: Exception on /destinations/0bc74d9d-8271-4493-bbe1-f20ceebd1769 [GET]
    Traceback (most recent call last):
    File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
    File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
     rv = self.handle_user_exception(e)
    File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
    File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
    File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
    File "/opt/regularroutes/virtualenv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
    File "/opt/regularroutes/server/apiserver.py", line 319, in destinations
    stop_clusters(stops, DEST_RADIUS_MAX * 2),
    File "/opt/regularroutes/server/pyfiles/common_helpers.py", line 624, in stop_clusters
    groups = do_cluster(dests, dest_merge, dest_dist, cluster_distance)
    File "/opt/regularroutes/server/pyfiles/common_helpers.py", line 673, in do_cluster
    item[:] = heapitem(item[2], (x[2] for x in heap))
    File "/opt/regularroutes/server/pyfiles/common_helpers.py", line 664, in heapitem
    d1] for d1 in dests if d1 is not d0)
    TypeError: unorderable types: dict() < dict()
